spring.application.name=student-api

# postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/student_db
spring.datasource.username=postgres
spring.datasource.password=admin551

# hibernate/jpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


